name: Apply SUSFS
on:
  workflow_dispatch:
jobs:
  update:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: 16.0-exp-2
      - name: Replace drivers/kernelsu
        run: |            
          git apply -p2 --directory=drivers/kernelsu patches/ksun-3.4.0-legacy-susfs.patch
     
      - name: Commit
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add -A drivers/kernelsu
          git commit -m "kernelsu: update KernelSU-Next to v3.4.0 legacy" || echo "nothing to commit"
          git push
